spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
